[package]
name = "rapi"
version = "0.1.0"
authors = ["Jason Kim <junchkim@ebay.com>"]

[dependencies]
xorshift = "0.1"
actix = "0.7"
actix-web = "0.7"
futures = "0.1"
tokio = "0.1"
tokio-timer = "0.2"
clap = "2.32"
