[package]
name = "rapi"
version = "0.1.0"
authors = ["Jason Kim <junchkim@ebay.com>"]

[dependencies]
#rocket = "0.3.15"
#rocket_codegen = "0.3.15"
xorshift = "0.1"
actix = "0.7.3"
actix-web = "0.7.3"